package com.crackneet.app;

import java.util.HashMap;
import java.util.Map;

public final class NcertNotes {
    private NcertNotes() {}

    private static final Map<String,String> NOTES = new HashMap<String,String>();
    static {
        // Biology — Class 11
        put("Biology","The Living World","Biology studies life and its diversity. NCERT focuses on growth, reproduction, metabolism, cellular organisation and response to stimuli as important characteristics of living organisms. Taxonomy uses identification, nomenclature and classification; binomial nomenclature gives each species a genus and specific epithet.");
        put("Biology","Biological Classification","Whittaker's five-kingdom system groups organisms using cell structure, body organisation, nutrition, reproduction and phylogeny. Monera are prokaryotic; Protista are mainly unicellular eukaryotes; Fungi are absorptive heterotrophs; Plantae are primarily photosynthetic; Animalia are ingestive heterotrophs.");
        put("Biology","Plant Kingdom","Major plant groups include algae, bryophytes, pteridophytes, gymnosperms and angiosperms. Remember the dominant phase, vascular tissue, seeds and reproductive structures of each group, and the alternation between gametophyte and sporophyte generations.");
        put("Biology","Animal Kingdom","Animal classification uses symmetry, germ layers, coelom, segmentation, notochord and level of organisation. High-yield phyla include Porifera, Cnidaria, Platyhelminthes, Aschelminthes, Annelida, Arthropoda, Mollusca, Echinodermata and Chordata.");
        put("Biology","Morphology of Flowering Plants","Root, stem and leaf show characteristic modifications for storage, support, climbing, protection and propagation. A flower has calyx, corolla, androecium and gynoecium; inflorescence, placentation, aestivation and fruit/seed characters are important identification points.");
        put("Biology","Anatomy of Flowering Plants","Plant tissues are meristematic or permanent. Xylem mainly conducts water and minerals; phloem transports organic food. Compare dicot and monocot root, stem and leaf anatomy, especially vascular-bundle arrangement and cambium.");
        put("Biology","Structural Organisation in Animals","Animal tissues include epithelial, connective, muscular and nervous tissues. In earthworm, cockroach and frog, focus on body organisation, systems and distinctive adaptations described by NCERT.");
        put("Biology","Cell: The Unit of Life","The cell is the structural and functional unit of life. Prokaryotes lack a membrane-bound nucleus and typical membrane-bound organelles, while eukaryotes have a true nucleus. Plasma membrane is selectively permeable; organelles have specialised functions.");
        put("Biology","Biomolecules","Carbohydrates, proteins, lipids and nucleic acids are major biomolecules. Proteins are polymers of amino acids; DNA and RNA are polymers of nucleotides. Enzymes are biological catalysts whose activity depends on conditions such as temperature and pH.");
        put("Biology","Cell Cycle and Cell Division","The cell cycle includes interphase and M phase. Mitosis maintains chromosome number and produces genetically similar daughter cells; meiosis reduces chromosome number and creates variation through recombination and independent assortment.");
        put("Biology","Transport in Plants","Water moves through plants mainly by xylem and food through phloem. Transpiration, cohesion-tension and root pressure contribute to water movement; pressure-flow explains translocation of organic solutes in phloem.");
        put("Biology","Mineral Nutrition","Plants require essential macro- and micronutrients. Nitrogen is central to amino acids, proteins and nucleic acids. Deficiency symptoms, nitrogen metabolism, biological nitrogen fixation and the role of Rhizobium are high-yield NCERT areas.");
        put("Biology","Photosynthesis in Higher Plants","Light reactions occur in thylakoid membranes and generate ATP and NADPH. The Calvin cycle fixes CO2 in the stroma. Compare C3 and C4 pathways, photorespiration, cyclic/non-cyclic photophosphorylation and factors affecting photosynthesis.");
        put("Biology","Respiration in Plants","Glycolysis occurs in the cytoplasm; pyruvate oxidation and the Krebs cycle occur in mitochondria, followed by oxidative phosphorylation. Anaerobic respiration gives fermentation products, while aerobic respiration yields much more ATP.");
        put("Biology","Plant Growth and Development","Growth is an irreversible increase in size and involves cell division, enlargement and differentiation. Plant growth regulators such as auxins, gibberellins, cytokinins, ethylene and ABA control development; photoperiodism and vernalisation regulate flowering.");
        put("Biology","Digestion and Absorption","Digestion converts complex food into absorbable molecules. Salivary, gastric, pancreatic and intestinal enzymes act along the alimentary canal. Most absorption occurs in the small intestine through villi and microvilli.");
        put("Biology","Breathing and Exchange of Gases","Ventilation moves air into and out of lungs, while gas exchange occurs across the alveolar membrane. Oxygen is transported mainly by haemoglobin; CO2 is transported largely as bicarbonate. Neural and chemical factors regulate breathing.");
        put("Biology","Body Fluids and Circulation","Blood contains plasma, RBCs, WBCs and platelets; lymph supports fluid balance and immunity. The human heart has four chambers and double circulation. Know the cardiac cycle, ECG basics, blood groups and clotting.");
        put("Biology","Excretory Products and their Elimination","The nephron is the functional unit of the kidney. Urine formation involves glomerular filtration, selective reabsorption and tubular secretion. Counter-current mechanisms help concentrate urine; ADH, RAAS and ANF contribute to regulation.");
        put("Biology","Locomotion and Movement","Movement may occur through cilia, flagella, muscles or skeletal structures. Skeletal muscle contraction uses actin, myosin, ATP and Ca2+. Sliding filament theory, neuromuscular junction and common skeletal disorders are important.");
        put("Biology","Neural Control and Coordination","Neurons receive and transmit electrical signals. A reflex arc provides rapid response; the CNS and PNS coordinate body functions. Synaptic transmission and the roles of cerebrum, cerebellum, medulla and hypothalamus are key revision points.");
        put("Biology","Chemical Coordination and Integration","Endocrine glands release hormones into blood. Pituitary, thyroid, parathyroid, adrenal, pancreas, pineal and gonads regulate growth, metabolism, reproduction and homeostasis. Negative feedback is a major control principle.");

        // Biology — Class 12
        put("Biology","Sexual Reproduction in Flowering Plants","Angiosperms reproduce through flowers. Microsporogenesis forms pollen grains and megasporogenesis forms the embryo sac. Pollination is followed by pollen-pistil interaction, double fertilisation, embryo/endosperm formation and development of seed and fruit.");
        put("Biology","Human Reproduction","Male and female reproductive systems produce gametes and reproductive hormones. Spermatogenesis occurs in testes and oogenesis in ovaries. Fertilisation normally occurs at the ampullary-isthmic junction; implantation, pregnancy and parturition follow coordinated hormonal changes.");
        put("Biology","Reproductive Health","Reproductive health includes physical, emotional and social well-being related to reproduction. Contraceptive methods, assisted reproductive technologies, prevention of sexually transmitted infections and awareness of reproductive rights are core NCERT topics.");
        put("Biology","Principles of Inheritance and Variation","Mendel's laws include segregation and independent assortment under appropriate conditions. Extensions include incomplete dominance, codominance, multiple alleles, linkage, crossing over and sex-linked inheritance. Mutations and recombination generate variation.");
        put("Biology","Molecular Basis of Inheritance","DNA stores hereditary information and replication is semiconservative. The central flow is DNA → RNA → protein. Transcription, RNA processing, translation, genetic code, regulation of gene expression, lac operon, DNA fingerprinting and the Human Genome Project are high-yield areas.");
        put("Biology","Evolution","Evolution explains descent with modification and diversity through time. Natural selection, variation, genetic drift, gene flow, mutation, recombination and reproductive isolation contribute to evolutionary change. Hardy-Weinberg equilibrium describes an ideal non-evolving population.");
        put("Biology","Human Health and Disease","Health depends on physical, mental and social well-being. Innate and acquired immunity protect the body; antibodies and memory cells provide specific responses. Disease-causing organisms, vaccination, cancer, AIDS and drug/alcohol abuse are important NCERT themes.");
        put("Biology","Microbes in Human Welfare","Microbes are used in curd, bread, cheese, antibiotics, organic acids, enzymes, sewage treatment, biogas and biofertilisers. Know the organism-product pairs and the principle of activated sludge and anaerobic digestion.");
        put("Biology","Biotechnology: Principles and Processes","Recombinant DNA technology uses restriction enzymes, DNA ligase, vectors and host cells. PCR amplifies DNA; gel electrophoresis separates DNA fragments. Cloning and expression depend on suitable vectors, selectable markers and controlled culture conditions.");
        put("Biology","Biotechnology and its Applications","Biotechnology is applied to insulin, vaccines, gene therapy, transgenic crops, Bt cotton and molecular diagnosis. Biosafety, ethical questions and intellectual-property concerns accompany modern biotechnology.");
        put("Biology","Organisms and Populations","Populations interact with abiotic factors and with other organisms. Growth patterns include exponential and logistic models. Competition, predation, parasitism, mutualism, commensalism and amensalism shape population and community relationships.");
        put("Biology","Ecosystem","An ecosystem contains biotic and abiotic components linked by energy flow and nutrient cycling. Producers capture energy; consumers and decomposers transfer and recycle matter. Food chains, pyramids, productivity, decomposition and ecological succession are key concepts.");
        put("Biology","Biodiversity and Conservation","Biodiversity occurs at genetic, species and ecosystem levels. Major threats include habitat loss, over-exploitation, alien species and co-extinctions. In-situ and ex-situ conservation, biodiversity hotspots, sacred groves and protected areas are important NCERT facts.");

        // Chemistry — Class 11/12
        put("Chemistry","Some Basic Concepts of Chemistry","Use the mole concept to connect mass, particles and chemical equations. Master molar mass, empirical/molecular formula, stoichiometry, limiting reagent, percentage composition and concentration terms such as molarity and molality.");
        put("Chemistry","Structure of Atom","Atoms contain a small dense nucleus and electrons in quantised states. Quantum numbers describe allowed electron states; Aufbau principle, Pauli exclusion and Hund's rule guide electronic configuration. Spectra reflect energy-level transitions.");
        put("Chemistry","Classification of Elements and Periodicity","Periodic properties arise from electronic configuration and effective nuclear charge. Across a period atomic radius generally decreases and ionisation enthalpy/electronegativity generally increase; down a group atomic size increases. Know common exceptions and trends.");
        put("Chemistry","Chemical Bonding and Molecular Structure","Ionic bonding involves electron transfer and electrostatic attraction; covalent bonding involves sharing. Lewis structures, formal charge, VSEPR, hybridisation, molecular orbital ideas, hydrogen bonding and polarity explain structure and properties.");
        put("Chemistry","Thermodynamics","First law relates heat, work and internal energy. Enthalpy changes describe heat at constant pressure; Hess's law combines reaction enthalpies. Entropy measures dispersal and Gibbs energy, ΔG = ΔH − TΔS, helps assess spontaneity.");
        put("Chemistry","Equilibrium","Chemical equilibrium is dynamic, with equal forward and reverse rates. Equilibrium constants describe composition; Le Chatelier's principle predicts response to changes in concentration, pressure and temperature. Acids and bases require pH, Ka/Kb, buffers and solubility concepts.");
        put("Chemistry","Redox Reactions","Oxidation is loss of electrons or increase in oxidation number; reduction is gain of electrons or decrease in oxidation number. Balance redox equations using oxidation-number or ion-electron methods and identify oxidising/reducing agents.");
        put("Chemistry","Organic Chemistry: Basic Principles","Organic chemistry relies on carbon bonding, functional groups, isomerism and reaction mechanisms. Learn IUPAC nomenclature, electronic effects, resonance, inductive effect, hyperconjugation, acidity/basicity and electrophile/nucleophile behaviour.");
        put("Chemistry","Hydrocarbons","Alkanes undergo substitution, alkenes/alkynes undergo addition and aromatic compounds undergo electrophilic substitution. Markovnikov orientation, peroxide effect, ozonolysis, aromaticity and important preparation/reaction conditions are high-yield.");
        put("Chemistry","Solutions","Solutions are homogeneous mixtures. Concentration may be expressed as molarity, molality, mole fraction or percentage. Raoult's law, ideal/non-ideal solutions, colligative properties, abnormal molar mass and van't Hoff factor are essential.");
        put("Chemistry","Electrochemistry","Galvanic cells convert chemical energy to electrical energy. Cell potential, Nernst equation, conductance, Kohlrausch law, electrolysis and Faraday laws connect ionic movement with electrical quantities. Spontaneity relates to cell potential and Gibbs energy.");
        put("Chemistry","Chemical Kinetics","Reaction rate depends on concentration, temperature and catalysts. Rate laws, order, molecularity, integrated equations for zero/first order reactions, half-life and Arrhenius equation are core numerical areas.");
        put("Chemistry","The d-and f-Block Elements","Transition elements show variable oxidation states, coloured ions, complex formation, catalytic behaviour and magnetic properties. Lanthanoid contraction explains similarities and trends; know common oxidation states and important compounds from NCERT.");
        put("Chemistry","Coordination Compounds","A coordination entity contains a central metal atom/ion bonded to ligands. Learn coordination number, nomenclature, isomerism, Werner theory, VBT/CFT basics, magnetic behaviour and applications of complexes.");
        put("Chemistry","Haloalkanes and Haloarenes","C–X bonds undergo substitution and elimination depending on substrate, nucleophile, solvent and conditions. Compare SN1/SN2, E1/E2, reactivity of alkyl versus aryl halides and important reactions such as Wurtz and Grignard formation.");
        put("Chemistry","Alcohols Phenols and Ethers","Alcohols contain –OH on saturated carbon; phenols have –OH attached to aromatic carbon; ethers contain R–O–R. Compare acidity, dehydration, oxidation, electrophilic substitution of phenol and cleavage of ethers.");
        put("Chemistry","Aldehydes Ketones and Carboxylic Acids","Carbonyl compounds undergo nucleophilic addition; aldehydes are generally more readily oxidised than ketones. Carboxylic acids show acidic behaviour and undergo characteristic substitution reactions. Learn named reactions and distinguishing tests from NCERT.");
        put("Chemistry","Amines","Amines are derivatives of ammonia and show basicity due to a lone pair on nitrogen. Compare aliphatic and aromatic amines, preparation methods, diazotisation, coupling reactions and important reactions of aniline.");
        put("Chemistry","Biomolecules","Carbohydrates include monosaccharides, disaccharides and polysaccharides; proteins are amino-acid polymers; nucleic acids are nucleotide polymers. Vitamins, enzymes and biological roles are frequently tested from NCERT tables and definitions.");

        // Physics — Class 11/12
        put("Physics","Physical World","Physics connects observation, measurement, laws and mathematical models. Understand the scope of classical and modern physics, fundamental forces and the importance of conservation laws and experimental reasoning.");
        put("Physics","Units and Measurements","Use SI base/derived units, dimensions, significant figures and error propagation. Dimensional analysis checks equations and derives relations, while significant figures communicate measurement precision.");
        put("Physics","Motion in a Straight Line","Displacement, velocity and acceleration describe one-dimensional motion. For constant acceleration, v = u + at, s = ut + 1/2 at² and v² = u² + 2as. Interpret x–t and v–t graphs carefully.");
        put("Physics","Motion in a Plane","Vectors describe two-dimensional motion. Projectile motion separates horizontal and vertical components; uniform circular motion has centripetal acceleration directed toward the centre. Resolve vectors before applying equations.");
        put("Physics","Laws of Motion","Newton's laws relate force, momentum and acceleration. Free-body diagrams are essential. Friction acts opposite relative motion/tendency; centripetal force is not a new force but the net inward force required for circular motion.");
        put("Physics","Work, Energy and Power","Work transfers energy through a force and displacement. Kinetic energy is 1/2 mv²; potential energy depends on the conservative force. Work-energy theorem, conservation of mechanical energy and power are key numerical tools.");
        put("Physics","System of Particles and Rotational Motion","Centre of mass simplifies multi-particle motion. Torque changes angular momentum; moment of inertia measures resistance to angular acceleration. Know τ = Iα, L = Iω for fixed-axis rotation and rolling without slipping.");
        put("Physics","Gravitation","Newton's law gives F = Gm1m2/r². Gravitational potential, escape speed, orbital speed, satellites and variation of g with altitude/depth are central. Kepler's laws describe planetary motion.");
        put("Physics","Mechanical Properties of Solids","Stress is force per area and strain is fractional deformation. Elastic moduli quantify response to stress; Hooke's law applies within the elastic limit. Young's modulus is especially important for wire-extension problems.");
        put("Physics","Mechanical Properties of Fluids","Pressure, buoyancy and fluid flow are governed by density and forces. Continuity expresses mass conservation; Bernoulli's equation connects pressure, speed and height for ideal flow. Viscosity and surface tension explain many everyday phenomena.");
        put("Physics","Thermal Properties of Matter","Temperature describes thermal state; heat is energy transfer due to temperature difference. Thermal expansion, calorimetry, specific/latent heat and heat transfer by conduction, convection and radiation are important applications.");
        put("Physics","Thermodynamics","The first law expresses energy conservation for thermodynamic systems. Processes include isothermal, adiabatic, isobaric and isochoric changes. The second law introduces entropy and the direction of spontaneous heat transfer.");
        put("Physics","Kinetic Theory","Gas pressure and temperature arise from microscopic molecular motion. Ideal-gas relations connect macroscopic variables with molecular kinetic energy. Equipartition and degrees of freedom help determine internal energy and heat capacities.");
        put("Physics","Oscillations","Simple harmonic motion has restoring acceleration proportional to displacement and opposite in direction. x = A cos(ωt + φ), v and a follow phase relationships; spring and simple-pendulum time periods are high-yield.");
        put("Physics","Waves","Waves transfer energy without net transport of matter. Mechanical waves need a medium; sound shows reflection, interference, beats and Doppler effect. Wave speed, frequency, wavelength and standing-wave conditions are core relations.");
        put("Physics","Electric Charges and Fields","Charge is conserved and quantised; Coulomb's law gives electrostatic force. Electric field and potential describe the effect of charges; Gauss's law is powerful for symmetric charge distributions.");
        put("Physics","Electrostatic Potential and Capacitance","Potential is work per unit charge and electric field relates to its spatial variation. Capacitors store energy in an electric field; combinations in series/parallel and dielectric effects are important.");
        put("Physics","Current Electricity","Current is charge flow and Ohm's law gives V = IR for ohmic conductors. Apply Kirchhoff's rules, resistivity relations, series/parallel combinations, cells and power formulas to circuit problems.");
        put("Physics","Moving Charges and Magnetism","Moving charges and currents produce magnetic fields. Lorentz force acts on charges in fields; Biot-Savart and Ampere laws calculate fields for standard geometries. Charged-particle motion in magnetic fields is a frequent NEET application.");
        put("Physics","Magnetism and Matter","Magnetic dipoles, bar magnets and materials respond to magnetic fields. Distinguish diamagnetic, paramagnetic and ferromagnetic behaviour and remember the relationship between magnetic moment and torque.");
        put("Physics","Electromagnetic Induction","Changing magnetic flux induces emf. Faraday's and Lenz's laws determine magnitude and direction; self/mutual induction and eddy currents explain practical devices such as generators and transformers.");
        put("Physics","Alternating Current","AC voltage/current vary periodically. RMS values, reactance, impedance, phase difference, resonance and power factor describe RLC circuits. In resonance, inductive and capacitive reactances are equal.");
        put("Physics","Electromagnetic Waves","Accelerating charges can produce electromagnetic radiation. EM waves are transverse, travel in vacuum at c and carry energy. Know the spectrum order from radio waves through microwaves, IR, visible, UV, X-rays and gamma rays.");
        put("Physics","Ray Optics and Optical Instruments","Reflection and refraction describe ray paths at mirrors and lenses. Use the mirror/lens formula, magnification and sign convention consistently. Total internal reflection, optical instruments and prism relations are high-yield.");
        put("Physics","Wave Optics","Wave nature explains interference, diffraction and polarisation. Young's double-slit experiment gives fringe width β = λD/d. Coherent sources, path difference and conditions for maxima/minima are essential.");
        put("Physics","Dual Nature of Radiation and Matter","Light shows particle behaviour through the photoelectric effect, while matter has de Broglie wavelength λ = h/p. Work function, threshold frequency and stopping potential connect photon energy with emitted electrons.");
        put("Physics","Atoms","Rutherford's model established a small nucleus; Bohr's model introduced quantised orbits for hydrogen-like atoms. Energy levels and spectral transitions follow quantisation relations; remember limitations of the Bohr model.");
        put("Physics","Nuclei","Nuclear size is approximately proportional to A^(1/3). Binding energy per nucleon explains nuclear stability; radioactive decay follows exponential law. Fission and fusion release energy through changes in nuclear binding energy.");
        put("Physics","Semiconductor Electronics: Materials, Devices and Simple Circuits","Semiconductors have controllable conductivity. Intrinsic/extrinsic types, p–n junctions, diode characteristics, rectification, LED, photodiode, solar cell and transistor basics are key NCERT concepts.");
    }

    private static void put(String subject,String chapter,String text){ NOTES.put(subject+"|"+chapter,text); }

    public static String get(String subject,String chapter){
        String v=NOTES.get(subject+"|"+chapter);
        if(v!=null) return v;
        return "NCERT quick revision: learn the chapter definitions, core laws/processes, diagrams, important examples, exceptions and NCERT tables. Revise the highlighted facts and then solve chapter-wise NEET MCQs.";
    }
}
