plugins { id("com.android.application") }

dependencies {
    implementation("com.android.billingclient:billing:9.1.0")
}

configurations.all {
    exclude(group = "org.jetbrains.kotlin", module = "kotlin-stdlib-jdk7")
    exclude(group = "org.jetbrains.kotlin", module = "kotlin-stdlib-jdk8")
}

android {
    namespace = "com.crackneet.app"
    compileSdk = 36

    buildFeatures {
        buildConfig = true
    }

    defaultConfig {
        applicationId = "com.crackneet.app"
        minSdk = 23
        targetSdk = 36
        versionCode = 3
        versionName = "2.0.0"
        buildConfigField("String", "BACKEND_URL", "\"https://crackneet-api.onrender.com\"")
    }

    signingConfigs {
        create("release") {
            val password = System.getenv("KEYSTORE_PASSWORD")
            val alias = System.getenv("KEY_ALIAS")
            if (password != null && alias != null) {
                storeFile = rootProject.file("crackneet-upload.jks")
                storePassword = password
                keyPassword = password
                this.keyAlias = alias
            }
        }
    }

    buildTypes {
        release {
            signingConfig = signingConfigs.getByName("release")
        }
    }
}

// The NCERT notes patch is generated by an automated workflow. Normalize only
// its generated method before compilation so Java source remains valid even if
// the workflow stored escaped newline markers.
tasks.named("preBuild") {
    doFirst {
        val mainFile = rootProject.file("app/src/main/java/com/crackneet/app/MainActivity.java")
        val text = mainFile.readText()
        val escapedBlock = """String noteText(String s,String ch){\n        return NcertNotes.get(s,ch);\n    }\n    String noteFlow"""
        val validBlock = """String noteText(String s,String ch){
        return NcertNotes.get(s,ch);
    }
    String noteFlow"""
        if (text.contains(escapedBlock)) {
            mainFile.writeText(text.replace(escapedBlock, validBlock))
        }
    }
}
